// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	domain "mini-reconciliation/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// GetBankTransactions mocks base method.
func (m *MockTransactionRepository) GetBankTransactions(ctx context.Context, paths []string) ([]domain.BankTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBankTransactions", ctx, paths)
	ret0, _ := ret[0].([]domain.BankTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBankTransactions indicates an expected call of GetBankTransactions.
func (mr *MockTransactionRepositoryMockRecorder) GetBankTransactions(ctx, paths interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBankTransactions", reflect.TypeOf((*MockTransactionRepository)(nil).GetBankTransactions), ctx, paths)
}

// GetSystemTransactions mocks base method.
func (m *MockTransactionRepository) GetSystemTransactions(ctx context.Context, path string) ([]domain.SystemTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemTransactions", ctx, path)
	ret0, _ := ret[0].([]domain.SystemTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemTransactions indicates an expected call of GetSystemTransactions.
func (mr *MockTransactionRepositoryMockRecorder) GetSystemTransactions(ctx, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemTransactions", reflect.TypeOf((*MockTransactionRepository)(nil).GetSystemTransactions), ctx, path)
}
